### ISSUE TITLE
Error: from tinyllava.eval.score.wanda import autograd_hacks

### ISSUE THREAD

**Issue by linhan12** [G-JWLee/COINCIDE_code#1]
"ModuleNotFoundError: No module named 'tinyllava.eval.score.wanda' "occurred for the code in line 22 in "COINCIDE_code/COINCIDE_cluster/tinyllava/eval/score/coincide/extract_embed.py"

**Comment by G-JWLee** [comment]
Thank you for your interest in our work and for pointing out the bug! I've just fixed the error and updated the file!
