### ISSUE TITLE
Vision-Flan file missing

### ISSUE THREAD

**Issue by nguyenrtm** [G-JWLee/COINCIDE_code#3]
Hi, the file tinyllava/eval/score/coincide/score_task_embed_tan.py seems to be missing and therefore the script for Vision-Flan cannot be run.

**Comment by G-JWLee** [comment]
Hi! Thank you for your interest! The LLaVA-1.5 VIT and Vision-Flan VIT share the same embedding extracting code. You can use the extract_embed.py code. I've corrected the outdated script.
