### ISSUE TITLE
"tinyllava.eval.score.SemDeDup.clustering" missing

### ISSUE THREAD

**Issue by bardisafa** [G-JWLee/COINCIDE_code#4]
Hi, the file "tinyllava.eval.score.SemDeDup.clustering.clustering" seems to be missing, and as a result, the "compute_centroids.py" file cannot be run.

**Comment by G-JWLee** [comment]
Thank you for pointing out the bug. I've just fixed the compute_centroids.py file.

**Comment by bardisafa** [comment]
Hi,

I have followed the codebase and extracted features for the entire LLaVA-1.5 dataset. However, when I run the spherical clustering code, the imbalance error of the clustering is not decreasing, and eventually all cluster centers are the same which leads to cosine_smilarities all equal to one:

<img width="729" alt="Screenshot 2024-10-22 at 1 25 53 AM" src="https://github.com/user-attachments/assets/8132cd3c-c13c-47ab-85c2-d6086d1598a4">

Could you please let me know what is the issue here?
