### ISSUE TITLE
Error in cluster_wise_prune.py

### ISSUE THREAD

**Issue by linhan12** [G-JWLee/COINCIDE_code#6]
Hi, I got the error "IndexError: index 5355 is out of bounds for axis 0 with size 5355" in cluster_wise_prune.py in line 98. Maybe  it is related with the size of cluster_density or cluster ??? Also I want to know why "clusters = np.unique(cluster_indices)" in line 75.
<img width="702" alt="截屏2024-10-22 10 16 47" src="https://github.com/user-attachments/assets/d56770b6-c201-4645-b0c8-4d206ecb860b">

**Comment by G-JWLee** [comment]
We should give nearest_cent.npy as --cluster_path's input for cluster_wise_prune.py. The updated script will work well. Also, the role of "clusters = np.unique(cluster_indices)" is to find the unique cluster indices from the K-means clustering results. Thank you!
