### ISSUE TITLE
An issue in cluster centers (all cosine similarities =1)

### ISSUE THREAD

**Issue by bardisafa** [G-JWLee/COINCIDE_code#7]
Hi,

I have followed the codebase and extracted features for the entire LLaVA-1.5 dataset. However, when I run the spherical clustering code, the imbalance error of the clustering does not decrease, and eventually, all cluster centers are the same which leads to cosine_smilarities all equal to one:

<img width="729" alt="Screenshot 2024-10-22 at 1 25 53 AM" src="https://github.com/user-attachments/assets/8132cd3c-c13c-47ab-85c2-d6086d1598a4">

Could you please let me know what the issue is here?

**Comment by G-JWLee** [comment]
Since our method refer to diverse layers of the reference model, the dimension size should be larger than 4096.
When I ran the code with my embeddings, there was no issue.
I believe the error stems from the embedding. Can you check if the argument value for extract_embed.py from extract_embed.sh has '3 7 11 15 19'?

**Comment by linhan12** [comment]
> Since our method refers to diverse layers from the reference model, the dimension size should be larger than 4096.
> When I ran the code with my embeddings, there was no issue.
> I believe the error stems from the embedding. Can you check if the argument value for extract_embed.py from extract_embed.sh has '3 7 11 15 19'?

My dimension size is 20480, but I still encountered this problem.
![截屏2024-10-22 18 47 14](https://github.com/user-attachments/assets/26a7f4a2-f34f-4a8c-aceb-725d24740e85)

**Comment by G-JWLee** [comment]
One possibility is the faiss module. We need faiss-gpu, not faiss-cpu. Can you check this one?

**Comment by linhan12** [comment]
> One possibility is the faiss module. We need faiss-gpu, not faiss-cpu. Can you check if the correct module is install? During my research, I installed using the command: conda install pytorch/label/nightly::faiss-gpu

Yes. I use fails-gpu=1.7.2 which is installed by pip.

**Comment by bardisafa** [comment]
> Since our method refers to diverse layers from the reference model, the dimension size should be larger than 4096. When I ran the code with my embeddings, there was no issue. I believe the error stems from the embedding. Can you check if the argument value for extract_embed.py from extract_embed.sh has '3 7 11 15 19'?

When I run with the dimension size of 20480, I still encounter the same issue. Could you please double check the faiss-gpu version and the clustering script you are using? Seems like the current K-Means does not move cluster centers...

**Comment by G-JWLee** [comment]
Mine uses faiss-gpu 1.8.0 (cuda12.1.1_nightly) version, and there are no differences in the scripts, compute_centroids.py and clustering.py. Could you check the faiss-gpu version? During my research, the faiss-gpu version was sensitive to the cuda version and pytorch version. Thus, I highly recommend you search for the appropriate version for your system.

**Comment by bardisafa** [comment]
> I also have the same issue ......

Hi, please let us know in case you were able to solve the issue. Thanks

**Comment by linhan12** [comment]
> Mine uses faiss-gpu 1.8.0 (cuda12.1.1_nightly) version, and there are no differences in the scripts, compute_centroids.py and clustering.py. Could you check the faiss-gpu version? During my research, the faiss-gpu version was sensitive to the cuda version and pytorch version. Thus, I highly recommend you search for the appropriate version for your system.

I install fails-gpu1.8.0 and rerun compute_centroids.py. The issue of imbalance is solved, but the objective score after 50 iterations, from the process of kmeans.train(data), is still large (i.e. 585839). Is it right?

**Comment by G-JWLee** [comment]
Good to hear that the imbalance is fixed. In my embedding, the K-means results in objective=618815 imbalance=1.272 nsplit=0. The overall objective scale seems to be similar.

**Comment by bardisafa** [comment]
Installing faiss-gpu1.8.0 solved my problem too. I am closing this issue. Thanks!
